export const freebiesList = [
  { id: "breakfast", name: "Free breakfast" },
  { id: "parking", name: "Free parking" },
  { id: "internet", name: "Free internet" },
  { id: "airportsh", name: "Free airport shuttle" },
  { id: "cancellation", name: "Free cancellation" },
];

export const amenitiesList = [
  "24hr front desk",
  "Air-conditioned",
  "Fitness",
  "Pool",
  "Wi-Fi",
  "Restaurant",
  "Spa",
  "Bar",
  "Laundry service",
  "Concierge",
  "Room service",
  "Free toiletries",
  "Hairdryer",
  "Mini-bar",
  "Safe",
  "Pet-friendly",
  "Parking",
  "Non-smoking rooms",
  "Wheelchair accessible",
  "Business center",
  "Meeting rooms",
  "Shuttle service",
  "Beach access",
  "Golf course",
  "Tennis court",
];
