export const freebiesList = [
  "Free breakfast",
  "Free parking",
  "Free internet",
  "Free airport shuttle",
  "Free cancellation",
];

export const amenitiesList = [
  "24hr front desk",
  "Air-conditioned",
  "Fitness",
  "Pool",
  "Wi-Fi",
  "Restaurant",
  "Spa",
  "Bar",
  "Laundry service",
  "Concierge",
  "Room service",
  "Free toiletries",
  "Hairdryer",
  "Mini-bar",
  "Safe",
  "Pet-friendly",
  "Parking",
  "Non-smoking rooms",
  "Wheelchair accessible",
  "Business center",
  "Meeting rooms",
  "Shuttle service",
  "Beach access",
  "Golf course",
  "Tennis court",
];
